name: first
on:
  workflow_dispatch
jobs:
  first_job:
    name: This is my first job
    runs-on: ubuntu-latest
    steps:
      - name: Show variables
        env:
          VAR1: This is
          VAR2: A Demo of
          VAR3: Github Actions
          VAR4: Workflow jobs
        run: |
          echo $VAR1 $VAR2 $VAR3 $VAR4
      - name: List data
        run: |
          touch first.txt
          echo "Show files"
          ls -a .
          pwd
        shell: bash
      - name: Next one
        run: |
          echo "Lets look again"
          ls -a .
        shell: bash
